version: 0.0
os: linux
files:
  - source: /home/ec2-user/cicd-pipeline-train-schedule-kubernetes
    destination: /home/ec2-user/train-schedule-app
hooks:
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ec2-user
