version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/cicd-pipeline-train-schedule-kubernetes
hooks:
  AfterInstall:
    # Install dependencies
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    # Start the server after installation
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
