version: 0.0
os: linux
files:
  - source: app.js
    destination: /var/www/html/app.js
  - source: public/
    destination: /var/www/html/public/
  - source: views/
    destination: /var/www/html/views/
  - source: Dockerfile
    destination: /var/www/html/Dockerfile

hooks:
  BeforeInstall:
    - location: scripts/pre_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
