version: 0.0
os: linux
files:
  - source: /  # Assuming the whole source directory needs to be copied
    destination: /home/ec2-user/train-schedule-app

hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
